version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  pykwalify.core:
    level: CRITICAL
    handlers: [console]
    propagate: no
  ezcluster.main:
    level: DEBUG
    handlers: [console]
    propagate: no
  ezcluster.groomer:
    level: DEBUG
    handlers: [console]
    propagate: no
  ezcluster.plugins:
    level: DEBUG
    handlers: [console]
    propagate: no
  ezcluster.generator:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: WARN
  handlers: [console]
